name = "SeuratRDS"
uuid = "dc2ff7d6-b19f-434a-a8eb-f50e20111c56"
authors = ["Matt Karikomi <mattkarikomi@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
